trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
      addToPath: true
  
  - script: |
      python3.7 -m pip install virtualenv
      virtualenv REAL_FOR_FGO_virtualenv
      source REAL_FOR_FGO_virtualenv/bin/activate
      python3.7 -m pip install --upgrade pip
      python -m pip install --upgrade setuptools wheel
      
      echo '\nWHICH python is running:'
      which python3.7
      
      echo '\npython version:'
      python3.7 --version

      echo '\ninstalled packages:'
      pip list

    displayName: 'Install Dependencies'
      


- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo "Hello from Windows (latest)!"
    displayName: 'echo cmd'