trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
      addToPath: true
  
  - script: |
      python3.7 -m pip install --upgrade pip
      python3.7 -m pip install virtualenv
      virtualenv REAL_FOR_FGO_virtualenv
      source REAL_FOR_FGO_virtualenv/bin/activate
      VAR_PYTHON_WHICH = which python3.7
      VAR_PYTHON_VERSION = python3.7 --version
      echo 'Which python: $VAR_PYTHON_WHICH'
      echo 'Version python: $VAR_PYTHON_VERSION'
      displayName: 'Install Dependencies'
      


- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo "Hello from Windows (latest)!"
    displayName: 'echo cmd'