trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo Hello from Ubuntu (latest)!

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Hello from Windows (latest)!  